/*
 * ui_assets.h -- generated by scripts/bake-ui-assets. Do not edit.
 *
 * Text: DejaVu Sans Mono, Bitstream Vera licence.
 * Icons: Font Awesome 4.7, SIL OFL 1.1.
 * Both licences are in assets/licenses.
 */
#ifndef MH_UI_ASSETS_H
#define MH_UI_ASSETS_H

#include <stddef.h>

/* One monospace face at one pixel size: every glyph occupies the
 * same cell, so a run of text is laid out by multiplying. */
typedef struct {
    unsigned size, advance, cell_w, cell_h, ascent;
    unsigned first, count;
    const unsigned char *alpha;   /* count * cell_w * cell_h */
} mh_ui_font_data;

typedef struct {
    unsigned size;
    const unsigned char *alpha;   /* size * size */
} mh_ui_icon_size;

typedef struct {
    const char *name;
    mh_ui_icon_size sizes[5];
} mh_ui_icon_data;

enum {
    MH_UI_ICON_ROMS = 0,
    MH_UI_ICON_POWER = 1,
    MH_UI_ICON_ROTATE = 2,
    MH_UI_ICON_DISPLAY = 3,
    MH_UI_ICON_STORAGE = 4,
    MH_UI_ICON_INSTALL = 5,
    MH_UI_ICON_OPTION = 6,
    MH_UI_ICON_SETTINGS = 7,
    MH_UI_ICON_PLAY = 8,
    MH_UI_ICON_TRASH = 9,
    MH_UI_ICON_EJECT = 10,
    MH_UI_ICON_STOP = 11,
    MH_UI_ICON_COUNT = 12
};

extern const mh_ui_font_data mh_ui_fonts[3];
extern const mh_ui_icon_data mh_ui_icons[MH_UI_ICON_COUNT];
extern const unsigned mh_ui_glyphs[202];
#define MH_UI_FONT_COUNT 3
#define MH_UI_FONT_COLUMNS 16
#define MH_UI_ICON_SIZES 5

#endif /* MH_UI_ASSETS_H */
